# Generated by Django 5.0.7 on 2024-07-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchmate", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchlist",
            name="link",
            field=models.URLField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
