# Generated by Django 5.0.7 on 2024-07-14 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("watchmate", "0002_watchlist_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="watchlist",
            name="link",
        ),
    ]
